apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - integration-test.yaml
  - scaledobject.yaml
  - service.yaml
  - servicemonitor.yaml
commonLabels:
  app.kubernetes.io/component: podinfo
configMapGenerator:
  - name: podinfo-cm
    literals:
      - "PODINFO_UI_COLOR=#34577c"
