apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  labels:
    app.kubernetes.io/component: podinfo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: podinfo
  endpoints:
    - port: http
      interval: 30s
