apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: ClusterIP
  clusterIP: None # headless service, since ingress-nginx uses endpoints
  selector:
    app.kubernetes.io/component: podinfo
  ports:
    - name: http
      port: 9898
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9999
      targetPort: grpc
      protocol: TCP
