apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-demo
resources:
  - ../../base
  - ingress-intern.yaml
  - ingress-services.yaml
commonLabels:
  app.kubernetes.io/name: demo
configMapGenerator:
  - name: podinfo-cm
    literals:
      - PODINFO_LEVEL=debug
    behavior: merge
  - name: test-config
    literals:
      - DEMO_SERVICE=demo2.test.has-to-be.services
